In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Load Data

In [5]:
TRAIN_PATH = './dataset/train.csv'
TEST_PATH = './dataset/test.csv'

assert os.path.exists(TRAIN_PATH) , "doesnt exist"
assert os.path.exists(TEST_PATH) , "doesnt exist"

train = pd.read_csv(TRAIN_PATH)
test = pd.read_csv(TEST_PATH)

In [8]:
print(train.shape)
train.head()

(15000, 13)

,id,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,0,6.9,0.725,0.00,2.4,0.093,14.0,31.0,0.99640,3.48,0.54,9.8,5.0
1,1,7.2,0.610,0.06,1.6,0.084,6.0,14.0,0.99765,3.53,0.75,10.9,7.0
2,2,9.3,0.310,0.34,2.7,0.084,32.0,71.0,0.99760,3.25,0.87,9.3,7.0
3,3,6.4,0.440,0.09,2.5,0.082,4.0,12.0,0.99498,3.32,0.84,9.8,6.0
4,4,7.8,0.540,0.00,1.8,0.080,15.0,37.0,0.99720,3.52,0.56,9.8,5.0

# Data quality

In [9]:
print(train.isnull().sum())

id                      0
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [10]:
print(train.isna().sum())

id                      0
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [12]:
print(train.duplicated().sum())

0

In [13]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    15000 non-null  int64
 1   fixed acidity         15000 non-null  float64
 2   volatile acidity      15000 non-null  float64
 3   citric acid           15000 non-null  float64
 4   residual sugar        15000 non-null  float64
 5   chlorides             15000 non-null  float64
 6   free sulfur dioxide   15000 non-null  float64
 7   total sulfur dioxide  15000 non-null  float64
 8   density               15000 non-null  float64
 9   pH                    15000 non-null  float64
 10  sulphates             15000 non-null  float64
 11  alcohol               15000 non-null  float64
 12  quality               15000 non-null  float64
dtypes: float64(12), int64(1)
memory usage: 1.5 MB

In [14]:
train.describe()

,id,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,7499.500000,8.150407,0.506026,0.229651,2.185944,0.078890,13.041077,36.893967,0.996907,3.323941,0.618216,10.183854,5.652467
std,4330.271354,1.389280,0.135077,0.178647,0.521511,0.014986,7.843052,23.956718,0.001392,0.116201,0.107910,0.900769,0.814861
min,0.000000,3.500000,0.180000,0.000000,1.100000,0.012000,0.650000,5.000000,0.990640,2.790000,0.400000,8.100000,3.000000
25%,3749.750000,7.200000,0.400000,0.050000,1.900000,0.073000,6.000000,19.000000,0.995880,3.240000,0.550000,9.500000,5.000000
50%,7499.500000,7.800000,0.510000,0.240000,2.100000,0.078000,11.000000,29.000000,0.996800,3.320000,0.590000,9.800000,6.000000
75%,11249.250000,8.900000,0.600000,0.370000,2.300000,0.084000,17.000000,48.000000,0.997800,3.390000,0.660000,10.800000,6.000000
max,14999.000000,15.800000,1.740000,0.770000,13.300000,0.415000,52.000000,152.000000,1.003690,4.010000,1.950000,15.000000,8.000000

In [ ]:
train['quality'].unique()