In [ ]:
# Install required packages if missing (uncomment if needed)
# !pip install numpy pandas matplotlib scikit-learn xgboost

# Clean imports for risk prediction model
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb

## Data Loading

In [9]:
TRAIN_PATH = 'dataset/train.csv'
TEST_PATH = 'dataset/test.csv'

assert os.path.exists(TRAIN_PATH) , f"This path {TRAIN_Path} doesnt exist. Make sure it exists"
assert os.path.exists(TEST_PATH) , f"This path {TEST_PATH} doesnt exist. Make sure it exists"

train = pd.read_csv(TRAIN_PATH)
test = pd.read_csv(TEST_PATH)

In [10]:
test.head()

,id,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents
0,517754,highway,2,0.34,45,night,clear,True,True,afternoon,True,True,1
1,517755,urban,3,0.04,45,dim,foggy,True,False,afternoon,True,False,0
2,517756,urban,2,0.59,35,dim,clear,True,False,afternoon,True,True,1
3,517757,rural,4,0.95,35,daylight,rainy,False,False,afternoon,False,False,2
4,517758,highway,2,0.86,35,daylight,clear,True,False,evening,False,True,3

# Feature and column

In [11]:
TARGET = 'accident_risk'
ID_COL = 'id'

FEATURES_COLS = [c for c in train.columns]
DROP_COLS = [ID_COL,TARGET]
COLS = [c for c in FEATURES_COLS if c not in DROP_COLS ]
print(COLS)

# Set categorical and numeric cols

CATEGORICAL_COLS = []
NUMERIQUES_COLS = []

for c in COLS:
    if c == ID_COL:
        continue
    if pd.api.types.is_numeric_dtype(train[c]):
        NUMERIQUES_COLS.append(c)
    else:
        CATEGORICAL_COLS.append(c)

le = LabelEncoder()

for col in COLS:
    train[col] = le.fit_transform(train[col])
    test[col] = le.fit_transform(test[col])

    
print(f"Numeric Columns",NUMERIQUES_COLS)
print(f"Categorical Columns",CATEGORICAL_COLS)

['road_type', 'num_lanes', 'curvature', 'speed_limit', 'lighting', 'weather', 'road_signs_present', 'public_road', 'time_of_day', 'holiday', 'school_season', 'num_reported_accidents']
Numeric Columns ['num_lanes', 'curvature', 'speed_limit', 'road_signs_present', 'public_road', 'holiday', 'school_season', 'num_reported_accidents']
Categorical Columns ['road_type', 'lighting', 'weather', 'time_of_day']

In [12]:
test.head()

,id,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents
0,517754,0,1,88,2,2,0,1,1,0,1,1,1
1,517755,2,2,4,2,1,1,1,0,0,1,0,0
2,517756,2,1,150,1,1,0,1,0,0,1,1,1
3,517757,1,3,189,1,0,2,0,0,0,0,0,2
4,517758,0,1,180,1,0,0,1,0,1,0,1,3

In [13]:
X_train_dev,X_test, y_train_dev , y_test = train_test_split(train[COLS],train[TARGET],test_size=0.15)

X_train,X_dev, y_train , y_dev = train_test_split(train[COLS],train[TARGET],test_size=0.2)

In [14]:
model_xgb = xgb.XGBRegressor()

model_rf = RandomForestRegressor()

In [15]:
model_xgb.fit(X_train,y_train)

model_rf.fit(X_train,y_train)

RandomForestRegressor()

In [16]:
y_pred_xgb = model_xgb.predict(X_dev)

y_pred_rf = model_rf.predict(X_dev)

In [17]:
rmse_xgb = root_mean_squared_error(y_dev,y_pred_xgb)

rmse_rf = root_mean_squared_error(y_dev,y_pred_rf)

print(f"RMSE XGB:{rmse_xgb}")

print(f"RMSE rf:{rmse_rf}")

RMSE XGB:0.05621040276839836
RMSE rf:0.059485092819642815

## Search best params

In [ ]:
params = {
    'n_estimators':[100,200,300,400,500,600],
    'learning_rate':[0.05,0.06,0.07,0.08,0.1,0.2],
    'subsample':[0.8,0.9,1],
}
grid = GridSearchCV(xgb.XGBRegressor(),params,cv=5)

print('start training...')
grid.fit(X_train_dev,y_train_dev)

start printing

# Pipeline

In [ ]:
numeric_transformer = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='mean')),
    ('scaler',StandardScaler())
])

categoric_transformer = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('encoder',OneHotEncoder(handle_unknown='ignore',sparse_output= False))
])

preprocess = ColumnTransformer(
   transformers = [
       ('num',numeric_transformer,NUMERIQUES_COLS),
       ('cat',categoric_transformer,CATEGORICAL_COLS)
   ]
)

model = xgb.XGBRegressor(
    n_estimators=300,
    learning_rate=0.08,
    subsample=0.9,
    random_state=42,
)

pipe = Pipeline(steps=[
    ('preprocess',preprocess),
    ('model',model)
]
)

In [ ]:
for i in range(1,10):
    n_dash = '*'.join('' for x in range(10-i))
    print(n_dash)
for i in range(1,10):
    n_dash = '*'.join('' for x in range(i))
    print(n_dash)

# Training

In [ ]:
pipe.fit(train[COLS],train[TARGET])

In [ ]:
y_predict = pipe.predict(test[COLS])

# Predicting

In [ ]:
y_predict.shape

In [ ]:
data = {
    ID_COL: test[ID_COL].values,
    TARGET:y_predict
}
submission = pd.DataFrame(data)

submission.to_csv('submission_roadaccident2.csv',index=False)